// pergunta.js (Cole exatamente isso)
export const bancoPerguntas = [

    { pergunta: "Qual campeão é conhecido como o 'Orgulho de Nazumah'?", opcoes: ["K'Sante", "Jax", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "Qual a cor da barra de energia do Kennen?", opcoes: ["Azul", "Amarela", "Branca", "Roxa"], correta: 1 },
    { pergunta: "Quantos jogadores há em cada equipa no Rift?", opcoes: ["3", "4", "5", "6"], correta: 2 },
    { pergunta: "Qual campeão atira cartas coloridas?", opcoes: ["Twisted Fate", "Ezreal", "Graves", "Lucian"], correta: 0 },
    { pergunta: "Qual o nome da passiva da Anivia?", opcoes: ["Gelo", "Renascimento", "Ovo", "Frio"], correta: 2 },
    { pergunta: "Quem é o suporte da Xayah?", opcoes: ["Rakan", "Thresh", "Braum", "Blitzcrank"], correta: 0 },
    { pergunta: "Qual destes campeões é um gato?", opcoes: ["Nidalee", "Yuumi", "Rengar", "Twitch"], correta: 1 },
    { pergunta: "Qual a arma principal da Caitlyn?", opcoes: ["Pistola", "Arco", "Rifle", "Besta"], correta: 2 },
    { pergunta: "Qual campeão tem uma Ultimate chamada 'Crescimento Gigante'?", opcoes: ["Cho'Gath", "Lulu", "Malphite", "Zac"], correta: 1 },
    { pergunta: "Qual monstro do rio dá regeneração de vida e mana?", opcoes: ["Dragão", "Aronguejo", "Barão", "Gromp"], correta: 1 },
    { pergunta: "Qual é o apelido da Lux?", opcoes: ["A Dama da Luz", "A Sombra", "A Lâmina", "A Estrela"], correta: 0 },
    { pergunta: "Quem é o pai da Cassiopeia e da Katarina?", opcoes: ["Swain", "Darius", "Du Couteau", "Garen"], correta: 2 },
    { pergunta: "Qual item é conhecido como 'Zhonya'?", opcoes: ["Cetro de Cristal", "Ampulheta de Zhonya", "Gume do Infinito", "Cajado do Vazio"], correta: 1 },
    { pergunta: "Qual destes feitiços dá um 'pulo' instantâneo?", opcoes: ["Fantasma", "Flash", "Exaustão", "Barreira"], correta: 1 },
    { pergunta: "Qual a nacionalidade do Braum?", opcoes: ["Demacia", "Freljord", "Noxus", "Ionia"], correta: 1 },
    { pergunta: "Qual campeão usa um escudo enorme e protege poros?", opcoes: ["Leona", "Braum", "Alistar", "Taric"], correta: 1 },
    { pergunta: "Qual campeão vira uma aranha?", opcoes: ["Elise", "Nidalee", "Zyra", "Evelynn"], correta: 0 },
    { pergunta: "Qual a classe do Garen?", opcoes: ["Mago", "Atirador", "Lutador/Tanque", "Suporte"], correta: 2 },
    { pergunta: "Qual o nome da cidade tecnológica vizinha de Zaun?", opcoes: ["Noxus", "Demacia", "Piltover", "Ionia"], correta: 2 },
    { pergunta: "Qual campeão puxa inimigos com uma âncora?", opcoes: ["Thresh", "Nautilus", "Blitzcrank", "Pyke"], correta: 1 },
    { pergunta: "Qual o elemento do Dragão que muda o mapa com matos?", opcoes: ["Fogo", "Oceano", "Nuvens", "Montanha"], correta: 1 },
    { pergunta: "Qual o elemento do Dragão que cria paredes novas?", opcoes: ["Fogo", "Oceano", "Nuvens", "Montanha"], correta: 3 },
    { pergunta: "Qual campeão é um espantalho?", opcoes: ["Fiddlesticks", "Shaco", "Nocturne", "Hecarim"], correta: 0 },
    { pergunta: "Qual o nome da arma da Miss Fortune?", opcoes: ["Chumbo Grosso", "Choque e Pavor", "Sussurro", "Besta"], correta: 1 },
    { pergunta: "Quantas skins de equipas campeãs mundiais existem?", opcoes: ["Nenhuma", "Muitas", "Uma por ano", "Apenas 3"], correta: 2 },
    { pergunta: "Qual campeã usa um chicote de espinhos?", opcoes: ["Zyra", "Leona", "Evelynn", "Lissandra"], correta: 2 },
    { pergunta: "Quem é o explorador de Piltover que usa uma manopla?", opcoes: ["Jayce", "Ezreal", "Vi", "Ekko"], correta: 1 },
    { pergunta: "Qual campeão come os inimigos para crescer?", opcoes: ["Cho'Gath", "Tahm Kench", "Nunu", "Gnar"], correta: 0 },
    { pergunta: "Qual o nome do urso do Volibear?", opcoes: ["Tibbers", "Daisy", "Ele próprio", "Ursa"], correta: 2 },
    { pergunta: "Qual a arma do Yasuo?", opcoes: ["Adaga", "Katana", "Machado", "Lança"], correta: 1 },
    { pergunta: "Qual campeão é um gladiador de Noxus?", opcoes: ["Draven", "Darius", "Katarina", "Talon"], correta: 0 },
    { pergunta: "O que o item 'Gume do Infinito' aumenta?", opcoes: ["Vida", "Dano Crítico", "Mana", "Velocidade"], correta: 1 },
    { pergunta: "Qual campeão é um rato da selva?", opcoes: ["Twitch", "Teemo", "Kennen", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeã joga bolas de fogo?", opcoes: ["Lux", "Annie", "Ahri", "Karma"], correta: 1 },
    { pergunta: "Qual campeã tem nove caudas?", opcoes: ["Ahri", "Evelynn", "Akali", "Kai'Sa"], correta: 0 },
    { pergunta: "Qual campeão usa um martelo que vira canhão?", opcoes: ["Jayce", "Poppy", "Ornn", "Tristana"], correta: 0 },
    { pergunta: "Qual feitiço de invocador serve para curar?", opcoes: ["Curar", "Incendiar", "Exaustão", "Clareza"], correta: 0 },
    { pergunta: "Qual campeão joga barris de bebida?", opcoes: ["Gragas", "Gangplank", "Singed", "Bardo"], correta: 0 },
    { pergunta: "Qual o nome da espada do Aatrox?", opcoes: ["Espada da Ruína", "A Lâmina Darkin", "Gume", "Excalibur"], correta: 1 },
    { pergunta: "Quem é a esposa de Lucian?", opcoes: ["Senna", "Vayne", "Quinn", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão é feito de rocha?", opcoes: ["Malphite", "Galio", "Rammus", "Skarner"], correta: 0 },
    { pergunta: "Qual o nome da Ultimate do Karthus?", opcoes: ["Requiem", "Final Spark", "Chuva de Flechas", "Impacto"], correta: 0 },
    { pergunta: "Qual campeão é um tubarão (ou invoca um)?", opcoes: ["Fizz", "Nami", "Pyke", "Nautilus"], correta: 0 },
    { pergunta: "Qual o nome da passiva do Yasuo?", opcoes: ["Vento", "Caminho do Vagabundo", "Crítico", "Escudo"], correta: 1 },
    { pergunta: "Quem é a xerife de Piltover?", opcoes: ["Vi", "Caitlyn", "Jinx", "Camille"], correta: 1 },
    { pergunta: "Qual campeão corre muito rápido e diz 'OK'?", opcoes: ["Singed", "Rammus", "Hecarim", "Master Yi"], correta: 1 },
    { pergunta: "Qual o nome da ilha onde vivem os fantasmas?", opcoes: ["Ionia", "Ilha das Sombras", "Bilgewater", "Targon"], correta: 1 },
    { pergunta: "Qual campeão usa lanternas para salvar aliados?", opcoes: ["Thresh", "Jax", "Lulu", "Karma"], correta: 0 },
    { pergunta: "Qual a cor do 'Red Buff'?", opcoes: ["Azul", "Verde", "Vermelho", "Amarelo"], correta: 2 },
    { pergunta: "Qual a cor do 'Blue Buff'?", opcoes: ["Azul", "Roxo", "Ciano", "Verde"], correta: 0 },
    { pergunta: "Qual campeão atira bananas (ataque básico)?", opcoes: ["Soraka", "Lulu", "Wukong", "Nidalee"], correta: 0 },
    { pergunta: "Qual o nome da arma do Gangplank?", opcoes: ["Pistola e Sabre", "Tridente", "Canhão", "Besta"], correta: 0 },
    { pergunta: "Qual campeão é um bardo?", opcoes: ["Bardo", "Sona", "Seraphine", "Taric"], correta: 0 },
    { pergunta: "Qual campeã toca harpa?", opcoes: ["Sona", "Seraphine", "Janna", "Nami"], correta: 0 },
    { pergunta: "Qual campeão é o mestre das sombras?", opcoes: ["Zed", "Shen", "Akali", "Kayn"], correta: 0 },
    { pergunta: "Qual campeão é o olho do crepúsculo?", opcoes: ["Shen", "Kennen", "Zed", "Lee Sin"], correta: 0 },
    { pergunta: "Qual campeão é um ninja médico?", opcoes: ["Akali", "Shen", "Kennen", "Lee Sin"], correta: 1 },
    { pergunta: "Qual campeão usa um boomerang?", opcoes: ["Gnar", "Sivir", "Akshan", "Draven"], correta: 1 },
    { pergunta: "Qual campeão vira uma mega criatura quando a fúria enche?", opcoes: ["Gnar", "Shyvana", "Tryndamere", "Renekton"], correta: 0 },
    { pergunta: "Qual campeão é um pirata?", opcoes: ["Gangplank", "Graves", "Pyke", "Nautilus"], correta: 0 },
    { pergunta: "Qual campeã usa cartas de Tarot?", opcoes: ["Lux", "Ahri", "Twisted Fate", "Leblanc"], correta: 2 },
    { pergunta: "Qual campeão é um palhaço assassino?", opcoes: ["Shaco", "Fiddlesticks", "Nocturne", "Pyke"], correta: 0 },
    { pergunta: "Qual campeã é a mãe da nidalee no folclore (brincadeira)?", opcoes: ["Neeko", "Zyra", "Lulu", "LeBlanc"], correta: 0 },
    { pergunta: "Qual campeão é um dragão de verdade?", opcoes: ["Aurelion Sol", "Shyvana", "Jarvan IV", "Pantheon"], correta: 0 },
    { pergunta: "Qual campeão forja itens na base?", opcoes: ["Ornn", "Braum", "Gragas", "Udyr"], correta: 0 },
    { pergunta: "Qual o nome do dragão da Annie?", opcoes: ["Tibbers", "Rex", "Daisy", "Bolinha"], correta: 0 },
    { pergunta: "Qual campeão usa uma pá?", opcoes: ["Yorick", "Sion", "Karthus", "Urgot"], correta: 0 },
    { pergunta: "Qual campeã é uma sereia?", opcoes: ["Nami", "Fizz", "Cassiopeia", "Morgana"], correta: 0 },
    { pergunta: "Qual campeã joga veneno no chão e corre?", opcoes: ["Singed", "Cassiopeia", "Twitch", "Teemo"], correta: 0 },
    { pergunta: "Qual campeão é o açougueiro das areias?", opcoes: ["Renekton", "Nasus", "Azir", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão é um deus egípcio chacal?", opcoes: ["Nasus", "Renekton", "Azir", "Xerath"], correta: 0 },
    { pergunta: "Qual campeão invoca soldados de areia?", opcoes: ["Azir", "Nasus", "Renekton", "Xerath"], correta: 0 },
    { pergunta: "Qual campeão é um golem de vapor?", opcoes: ["Blitzcrank", "Viktor", "Orianna", "Urgot"], correta: 0 },
    { pergunta: "Qual campeã é uma boneca robô?", opcoes: ["Orianna", "Gwen", "Annie", "Zoe"], correta: 0 },
    { pergunta: "Qual campeã usa tesouras gigantes?", opcoes: ["Gwen", "Camille", "Fiora", "Irelia"], correta: 0 },
    { pergunta: "Qual campeã é a grande duelista?", opcoes: ["Fiora", "Irelia", "Riven", "Camille"], correta: 0 },
    { pergunta: "Qual campeã usa pernas de lâmina?", opcoes: ["Camille", "Fiora", "Katarina", "Evelynn"], correta: 0 },
    { pergunta: "Qual campeão é o rei dos trolls?", opcoes: ["Trundle", "Gragas", "Olaf", "Braum"], correta: 0 },
    { pergunta: "Qual campeão usa um machado e não morre na ult?", opcoes: ["Tryndamere", "Olaf", "Darius", "Sion"], correta: 0 },
    { pergunta: "Qual campeão é o mestre do metal?", opcoes: ["Mordekaiser", "Taric", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "Qual campeã é a luz de Demacia?", opcoes: ["Lux", "Morgana", "Kayle", "Vayne"], correta: 0 },
    { pergunta: "Qual campeã é o anjo caído?", opcoes: ["Morgana", "Kayle", "Leblanc", "Sivir"], correta: 0 },
    { pergunta: "Qual campeã é a guardiã do martelo?", opcoes: ["Poppy", "Tristana", "Lulu", "Yuumi"], correta: 0 },
    { pergunta: "Qual campeã é a artilheira Yordle?", opcoes: ["Tristana", "Poppy", "Lulu", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeão joga bombas?", opcoes: ["Ziggs", "Zilean", "Teemo", "Heimerdinger"], correta: 0 },
    { pergunta: "Qual campeão controla o tempo?", opcoes: ["Zilean", "Ekko", "Lucian", "Ryze"], correta: 0 },
    { pergunta: "Qual campeão viaja no tempo com a ult?", opcoes: ["Ekko", "Zilean", "Ezreal", "Jayce"], correta: 0 },
    { pergunta: "Qual campeão é o mago das runas?", opcoes: ["Ryze", "Brand", "Malzahar", "Kassadin"], correta: 0 },
    { pergunta: "Qual campeão é o mago de fogo?", opcoes: ["Brand", "Annie", "Ryze", "Xerath"], correta: 0 },
    { pergunta: "Qual campeão é o profeta do vazio?", opcoes: ["Malzahar", "Kassadin", "Kha'Zix", "Vel'Koz"], correta: 0 },
    { pergunta: "Qual campeão é um polvo do vazio com lasers?", opcoes: ["Vel'Koz", "Kha'Zix", "Cho'Gath", "Kog'Maw"], correta: 0 },
    { pergunta: "Qual campeão é o louco de Zaun?", opcoes: ["Dr. Mundo", "Singed", "Twitch", "Warwick"], correta: 0 },
    { pergunta: "Qual campeão é um lobisomem?", opcoes: ["Warwick", "Nidalee", "Udyr", "Rengar"], correta: 0 },
    { pergunta: "Qual campeão é um leão caçador?", opcoes: ["Rengar", "Nidalee", "Warwick", "Khazix"], correta: 0 },
    { pergunta: "Qual campeão é um inseto que evolui?", opcoes: ["Kha'Zix", "Rengar", "Skarner", "Elise"], correta: 0 },
    { pergunta: "Qual campeão usa um chicote de luz (lança)?", opcoes: ["Xin Zhao", "Jarvan IV", "Pantheon", "Jax"], correta: 0 },
    { pergunta: "Qual campeão é o príncipe de Demacia?", opcoes: ["Jarvan IV", "Garen", "Lux", "Galio"], correta: 0 },
    { pergunta: "Qual campeão é o artesão da guerra?", opcoes: ["Pantheon", "Aatrox", "Mordekaiser", "Sion"], correta: 0 },
    { pergunta: "Qual campeão é uma gárgula?", opcoes: ["Galio", "Malphite", "Maokai", "Ivern"], correta: 0 },
    { pergunta: "Qual campeão é uma árvore viva?", opcoes: ["Maokai", "Ivern", "Malphite", "Zyra"], correta: 0 },
    { pergunta: "Qual campeão é o 'Pai do Verde'?", opcoes: ["Ivern", "Maokai", "Bard", "Lulu"], correta: 0 },
    { pergunta: "Qual campeã usa um arco de gelo?", opcoes: ["Ashe", "Sejuani", "Sivir", "Vayne"], correta: 0 },
    { pergunta: "Qual campeã monta num javali gigante?", opcoes: ["Sejuani", "Rell", "Kled", "Nunu"], correta: 0 },
    { pergunta: "Qual campeão monta num lagarto chamado Skaarl?", opcoes: ["Kled", "Renekton", "Gnar", "Heimerdinger"], correta: 0 },
    { pergunta: "Qual campeã é a caçadora noturna?", opcoes: ["Vayne", "Kai'Sa", "Quinn", "Evelynn"], correta: 0 },
    { pergunta: "Qual campeã voa com uma águia chamada Valor?", opcoes: ["Quinn", "Anivia", "Kayle", "Galio"], correta: 0 },
    { pergunta: "Qual campeão é o mestre das cartas?", opcoes: ["Twisted Fate", "Shaco", "Zed", "Graves"], correta: 0 },
    { pergunta: "Qual campeão usa uma espingarda de cano duplo?", opcoes: ["Graves", "Lucian", "Jhin", "Miss Fortune"], correta: 0 },
    { pergunta: "Qual campeão é o virtuoso que conta até 4?", opcoes: ["Jhin", "Draven", "Ezreal", "Varus"], correta: 0 },
    { pergunta: "Qual campeã usa uma metralhadora chamada Pow-Pow?", opcoes: ["Jinx", "Tristana", "Zeri", "Samira"], correta: 0 },
    { pergunta: "Qual campeã é a filha do vazio?", opcoes: ["Kai'Sa", "Bel'Veth", "Rek'Sai", "Cassiopeia"], correta: 0 },
    { pergunta: "Qual campeã é a imperatriz do vazio?", opcoes: ["Bel'Veth", "Rek'Sai", "Kai'Sa", "Zyra"], correta: 0 },
    { pergunta: "Qual campeã é a escavadora do vazio?", opcoes: ["Rek'Sai", "Skarner", "Cho'Gath", "Kog'Maw"], correta: 0 },
    { pergunta: "Qual campeão é um escorpião de cristal?", opcoes: ["Skarner", "Rammus", "Malphite", "Anivia"], correta: 0 },
    { pergunta: "Qual campeão é o 'Coração de Ouro' de Freljord?", opcoes: ["Braum", "Olaf", "Gragas", "Udyr"], correta: 0 },
    { pergunta: "Qual campeão usa um barril explosivo na ult?", opcoes: ["Gragas", "Gangplank", "Ziggs", "Corki"], correta: 0 },
    { pergunta: "Qual campeão pilota um avião?", opcoes: ["Corki", "Rumble", "Heimerdinger", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeão pilota um robô de sucata?", opcoes: ["Rumble", "Blitzcrank", "Viktor", "Ekko"], correta: 0 },
    { pergunta: "Qual campeão coloca torres (turrets) no chão?", opcoes: ["Heimerdinger", "Zyra", "Shaco", "Maokai"], correta: 0 },
    { pergunta: "Qual campeã coloca plantas que atiram?", opcoes: ["Zyra", "Lulu", "Neeko", "Karma"], correta: 0 },
    { pergunta: "Qual campeã se disfarça de outros campeões?", opcoes: ["Neeko", "LeBlanc", "Ahri", "Evelynn"], correta: 0 },
    { pergunta: "Qual campeã é a mestre das ilusões?", opcoes: ["LeBlanc", "Neeko", "Zoe", "Lux"], correta: 0 },
    { pergunta: "Qual campeã é o aspecto do crepúsculo?", opcoes: ["Zoe", "Diana", "Leona", "Soraka"], correta: 0 },
    { pergunta: "Qual campeã é o aspecto da lua?", opcoes: ["Diana", "Zoe", "Leona", "Morgana"], correta: 0 },
    { pergunta: "Qual campeã é o aspecto do sol?", opcoes: ["Leona", "Diana", "Lux", "Seraphine"], correta: 0 },
    { pergunta: "Qual campeã é a filha das estrelas?", opcoes: ["Soraka", "Janna", "Karma", "Sona"], correta: 0 },
    { pergunta: "Qual campeã controla o vento?", opcoes: ["Janna", "Yasuo", "Yone", "Taliyah"], correta: 0 },
    { pergunta: "Qual campeã controla as pedras e rochas?", opcoes: ["Taliyah", "Malphite", "Rammus", "Taric"], correta: 0 },
    { pergunta: "Qual campeão é o cavaleiro de gemas?", opcoes: ["Taric", "Skarner", "Ezreal", "Jayce"], correta: 0 },
    { pergunta: "Qual campeão é o mestre do Yi?", opcoes: ["Wukong (aluno)", "Lee Sin", "Jax", "Ninguém"], correta: 0 },
    { pergunta: "Qual o nome da arma do Wukong?", opcoes: ["Cajado", "Espada", "Lança", "Machado"], correta: 0 },
    { pergunta: "Qual campeão é o mestre das armas?", opcoes: ["Jax", "Fiora", "Master Yi", "Aatrox"], correta: 0 },
    { pergunta: "Qual campeão usa o estilo Wuju?", opcoes: ["Master Yi", "Wukong", "Yasuo", "Yone"], correta: 0 },
    { pergunta: "Qual campeão é um ninja de eletricidade?", opcoes: ["Kennen", "Zed", "Shen", "Akali"], correta: 0 },
    { pergunta: "Qual campeã usa 'kunais' e bombas de fumaça?", opcoes: ["Akali", "Katarina", "Talon", "Zed"], correta: 0 },
    { pergunta: "Qual campeã usa adagas e reseta a ult ao matar?", opcoes: ["Katarina", "Akali", "Samira", "Vayne"], correta: 0 },
    { pergunta: "Qual campeão usa lâminas que saem da capa?", opcoes: ["Talon", "Katarina", "Zed", "Shaco"], correta: 0 },
    { pergunta: "Qual campeão é o monge cego?", opcoes: ["Lee Sin", "Jax", "Udyr", "Master Yi"], correta: 0 },
    { pergunta: "Qual campeão troca de 'posturas' de animais?", opcoes: ["Udyr", "Nidalee", "Shyvana", "Volibear"], correta: 0 },
    { pergunta: "Qual campeã vira um puma?", opcoes: ["Nidalee", "Rengar", "Warwick", "Gnar"], correta: 0 },
    { pergunta: "Qual campeão é um dragão que cospe fogo?", opcoes: ["Shyvana", "Aurelion Sol", "Jarvan IV", "Brand"], correta: 0 },
    { pergunta: "Qual campeão é o deus do trovão de Freljord?", opcoes: ["Volibear", "Ornn", "Anivia", "Braum"], correta: 0 },
    { pergunta: "Qual campeão é o deus da forja?", opcoes: ["Ornn", "Volibear", "Braum", "Gragas"], correta: 0 },
    { pergunta: "Qual campeã é a fênix de gelo?", opcoes: ["Anivia", "Ashe", "Lissandra", "Sejuani"], correta: 0 },
    { pergunta: "Qual campeã é a bruxa gélida?", opcoes: ["Lissandra", "Anivia", "Ashe", "Leblanc"], correta: 0 },
    { pergunta: "Qual campeão usa correntes para roubar ults?", opcoes: ["Sylas", "Thresh", "Nautilus", "Pyke"], correta: 0 },
    { pergunta: "Qual campeã usa correntes e é de Noxus?", opcoes: ["Leblanc", "Samira", "Katarina", "Rell"], correta: 3 },
    { pergunta: "Qual campeã usa uma espada e pistolas (estilo DMC)?", opcoes: ["Samira", "Miss Fortune", "Lucian", "Jinx"], correta: 0 },
    { pergunta: "Qual campeão usa uma espada gigante e é imortal na ult?", opcoes: ["Tryndamere", "Aatrox", "Garen", "Darius"], correta: 0 },
    { pergunta: "Qual campeão é o braço direito de Swain?", opcoes: ["Darius", "Draven", "Talon", "Katarina"], correta: 0 },
    { pergunta: "Qual campeão joga machados e é um carrasco?", opcoes: ["Draven", "Darius", "Olaf", "Sion"], correta: 0 },
    { pergunta: "Qual campeão renasce como um zumbi gigante?", opcoes: ["Sion", "Karthus", "Yorick", "Mordekaiser"], correta: 0 },
    { pergunta: "Qual campeão é o senhor da morte?", opcoes: ["Mordekaiser", "Sion", "Aatrox", "Thresh"], correta: 0 },
    { pergunta: "Qual campeão é o pastor de almas?", opcoes: ["Yorick", "Thresh", "Senna", "Lucian"], correta: 0 },
    { pergunta: "Qual campeão é o imperador de Shurima?", opcoes: ["Azir", "Xerath", "Nasus", "Renekton"], correta: 0 },
    { pergunta: "Qual campeão é um ser de energia pura?", opcoes: ["Xerath", "Azir", "Brand", "Ryze"], correta: 0 },
    { pergunta: "Qual campeão é o mestre da areia?", opcoes: ["Nasus", "Azir", "Renekton", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão é o crocodilo furioso?", opcoes: ["Renekton", "Nasus", "Sobek", "Warwick"], correta: 0 },
    { pergunta: "Qual campeã usa uma lâmina em cruz (boomerang)?", opcoes: ["Sivir", "Akshan", "Gnar", "Draven"], correta: 0 },
    { pergunta: "Qual campeão usa um gancho e revive aliados?", opcoes: ["Akshan", "Ezreal", "Graves", "Lucian"], correta: 0 },
    { pergunta: "Qual campeão é um explorador que dispara energia?", opcoes: ["Ezreal", "Akshan", "Lucian", "Jayce"], correta: 0 },
    { pergunta: "Qual campeão usa o martelo de Orlon?", opcoes: ["Poppy", "Jayce", "Ornn", "Braum"], correta: 0 },
    { pergunta: "Qual campeão usa o martelo e o canhão de Mercúrio?", opcoes: ["Jayce", "Viktor", "Ekko", "Vi"], correta: 0 },
    { pergunta: "Qual campeão é o arauto da evolução?", opcoes: ["Viktor", "Jayce", "Singed", "Blitzcrank"], correta: 0 },
    { pergunta: "Qual campeã usa manoplas gigantes?", opcoes: ["Vi", "Jinx", "Caitlyn", "Camille"], correta: 0 },
    { pergunta: "Qual campeão usa o tempo para voltar 4 segundos?", opcoes: ["Ekko", "Zilean", "Lucian", "Ezreal"], correta: 0 },
    { pergunta: "Qual campeão usa bombas e acelera aliados?", opcoes: ["Zilean", "Ekko", "Ziggs", "Heimerdinger"], correta: 0 },
    { pergunta: "Qual campeã usa uma bola robótica?", opcoes: ["Orianna", "Annie", "Lulu", "Yuumi"], correta: 0 },
    { pergunta: "Qual campeão é um golem de ferro?", opcoes: ["Blitzcrank", "Nautilus", "Malphite", "Galio"], correta: 0 },
    { pergunta: "Qual campeão puxa inimigos com uma mão metálica?", opcoes: ["Blitzcrank", "Thresh", "Nautilus", "Pyke"], correta: 0 },
    { pergunta: "Qual campeão é um mergulhador com uma âncora?", opcoes: ["Nautilus", "Pyke", "Fizz", "Nami"], correta: 0 },
    { pergunta: "Qual campeão é o estripador das águas sangrentas?", opcoes: ["Pyke", "Nautilus", "Gangplank", "Graves"], correta: 0 },
    { pergunta: "Qual campeão é um peixe malandro com um tridente?", opcoes: ["Fizz", "Nami", "Pyke", "Tahm Kench"], correta: 0 },
    { pergunta: "Qual campeão é o rei do rio (sapo/bagre)?", opcoes: ["Tahm Kench", "Gragas", "Braum", "Fizz"], correta: 0 },
    { pergunta: "Qual campeã usa bolhas e ondas de água?", opcoes: ["Nami", "Fizz", "Cassiopeia", "Morgana"], correta: 0 },
    { pergunta: "Qual campeã é uma medusa que petrifica?", opcoes: ["Cassiopeia", "Nami", "Morgana", "Zyra"], correta: 0 },
    { pergunta: "Qual campeã usa correntes e um escudo negro?", opcoes: ["Morgana", "Lux", "Lulu", "Karma"], correta: 0 },
    { pergunta: "Qual campeã tem asas e evolui no nível 6, 11 e 16?", opcoes: ["Kayle", "Morgana", "Anivia", "Quinn"], correta: 0 },
    { pergunta: "Qual campeão é um gárgula que protege Demacia?", opcoes: ["Galio", "Malphite", "Sion", "Maokai"], correta: 0 },
    { pergunta: "Qual campeão é o poder de Demacia?", opcoes: ["Garen", "Jarvan IV", "Lux", "Galio"], correta: 0 },
    { pergunta: "Qual campeã é a dama da luz?", opcoes: ["Lux", "Morgana", "Seraphine", "Sona"], correta: 0 },
    { pergunta: "Qual campeão é o exemplo de Demacia?", opcoes: ["Jarvan IV", "Garen", "Xin Zhao", "Lucian"], correta: 0 },
    { pergunta: "Qual campeão é o senescal de Demacia?", opcoes: ["Xin Zhao", "Jarvan IV", "Garen", "Galio"], correta: 0 },
    { pergunta: "Qual campeão usa uma lança e salta no ar?", opcoes: ["Pantheon", "Jarvan IV", "Xin Zhao", "Jax"], correta: 0 },
    { pergunta: "Qual campeão é o forjador de estrelas?", opcoes: ["Aurelion Sol", "Taric", "Soraka", "Bard"], correta: 0 },
    { pergunta: "Qual campeão coleta sinos pelo mapa?", opcoes: ["Bard", "Ivern", "Lulu", "Zoe"], correta: 0 },
    { pergunta: "Qual campeã é uma fada que usa o Pix?", opcoes: ["Lulu", "Yuumi", "Zoe", "Neeko"], correta: 0 },
    { pergunta: "Qual campeã é um gato que voa num livro?", opcoes: ["Yuumi", "Lulu", "Annie", "Nidalee"], correta: 0 },
    { pergunta: "Qual campeã usa um urso chamado Tibbers?", opcoes: ["Annie", "Lulu", "Gwen", "Zoe"], correta: 0 },
    { pergunta: "Qual campeã usa tesouras mágicas?", opcoes: ["Gwen", "Fiora", "Camille", "Irelia"], correta: 0 },
    { pergunta: "Qual campeã usa lâminas voadoras e dança?", opcoes: ["Irelia", "Fiora", "Katarina", "Akali"], correta: 0 },
    { pergunta: "Qual campeã é a duelista imbatível?", opcoes: ["Fiora", "Irelia", "Camille", "Riven"], correta: 0 },
    { pergunta: "Qual campeã usa uma espada quebrada?", opcoes: ["Riven", "Fiora", "Aatrox", "Yasuo"], correta: 0 },
    { pergunta: "Qual campeão é o mestre da vingança?", opcoes: ["Aatrox", "Varus", "Kayn", "Zed"], correta: 0 },
    { pergunta: "Qual campeão tem um arco e flechas de luz?", opcoes: ["Varus", "Ashe", "Ezreal", "Jhin"], correta: 0 },
    { pergunta: "Qual campeão usa uma foice e vira um assassino ou um darkin?", opcoes: ["Kayn", "Aatrox", "Varus", "Thresh"], correta: 0 },
    { pergunta: "Qual campeão é o ceifador de almas?", opcoes: ["Karthus", "Thresh", "Yorick", "Kayn"], correta: 0 },
    { pergunta: "Qual campeão usa uma pá e invoca fantasmas?", opcoes: ["Yorick", "Karthus", "Sion", "Urgot"], correta: 0 },
    { pergunta: "Qual campeão é metade humano metade aranha?", opcoes: ["Elise", "Nidalee", "Cassiopeia", "Shyvana"], correta: 0 },
    { pergunta: "Qual campeão é um caranguejo mecânico gigante?", opcoes: ["Urgot", "Skarner", "Nautilus", "Blitzcrank"], correta: 0 },
    { pergunta: "Qual campeã usa uma sniper e coloca armadilhas de bolo?", opcoes: ["Caitlyn", "Jinx", "Ashe", "Vayne"], correta: 0 },
    { pergunta: "Qual campeão é o mestre das correntes de Demacia?", opcoes: ["Sylas", "Jarvan IV", "Garen", "Xin Zhao"], correta: 0 },
    { pergunta: "Qual campeão é feito de fumo e sombras?", opcoes: ["Nocturne", "Shaco", "Fiddlesticks", "Hecarim"], correta: 0 },
    { pergunta: "Qual campeão é o cavaleiro fantasma?", opcoes: ["Hecarim", "Mordekaiser", "Karthus", "Sion"], correta: 0 },
    { pergunta: "Qual campeã usa um espelho e é de Ionia?", opcoes: ["Ahri", "Irelia", "Karma", "Leblanc"], correta: 0 },
    { pergunta: "Qual campeã é a iluminada de Ionia?", opcoes: ["Karma", "Lulu", "Lux", "Morgana"], correta: 0 },
    { pergunta: "Qual campeão usa machados que giram (e deve apanhá-los)?", opcoes: ["Draven", "Olaf", "Darius", "Sion"], correta: 0 },
    { pergunta: "Qual campeão tem uma passiva que lhe dá vida ao comer tropas?", opcoes: ["Cho'Gath", "Nunu", "Tahm Kench", "Gnar"], correta: 0 },
    { pergunta: "Qual campeão é um Yeti montado por um rapaz?", opcoes: ["Nunu e Willump", "Kled", "Sejuani", "Annie"], correta: 0 },
    { pergunta: "Qual campeão atira um barril que dá lentidão?", opcoes: ["Gragas", "Gangplank", "Singed", "Bardo"], correta: 0 },
    { pergunta: "Qual campeão deixa um rastro de veneno por onde passa?", opcoes: ["Singed", "Twitch", "Cassiopeia", "Teemo"], correta: 0 },
    { pergunta: "Qual campeã é uma atiradora que usa uma besta de pulso?", opcoes: ["Vayne", "Kai'Sa", "Quinn", "Sivir"], correta: 0 },
    { pergunta: "Qual o nome da Ultimate do Garen?", opcoes: ["Justiça Demaciana", "Impacto Meteoro", "Giro da Vitória", "Corte Fatal"], correta: 0 },
    { pergunta: "Qual campeão é conhecido como 'O Coração da Tempestade'?", opcoes: ["Kennen", "Volibear", "Anivia", "Janna"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Lótus da Morte'?", opcoes: ["Katarina", "Samira", "Akali", "Fiora"], correta: 0 },
    { pergunta: "Qual campeão é um suporte que usa um sino e portais?", opcoes: ["Bardo", "Thresh", "Zilean", "Ivern"], correta: 0 },
    { pergunta: "Qual campeã usa um leque de metal?", opcoes: ["Karma", "Akali", "Sivir", "Irelia"], correta: 0 },
    { pergunta: "Qual campeão é o irmão de Nasus?", opcoes: ["Renekton", "Azir", "Xerath", "Rammus"], correta: 0 },
    { pergunta: "Qual campeão é o arqueiro Darkin?", opcoes: ["Varus", "Aatrox", "Kayn", "Rhaast"], correta: 0 },
    { pergunta: "Qual campeã usa uma espada que se divide em várias?", opcoes: ["Irelia", "Fiora", "Riven", "Samira"], correta: 0 },
    { pergunta: "Qual campeão usa uma metralhadora e fuma um charuto?", opcoes: ["Graves", "Lucian", "Gangplank", "Jhin"], correta: 0 },
    { pergunta: "Qual campeão é conhecido como 'O Terror das Profundezas'?", opcoes: ["Nautilus", "Fizz", "Pyke", "Thresh"], correta: 0 },
    { pergunta: "Qual campeã é uma Yordle que usa um canhão?", opcoes: ["Tristana", "Poppy", "Lulu", "Vex"], correta: 0 },
    { pergunta: "Qual campeão tem a habilidade 'Sentença' (Gancho)?", opcoes: ["Thresh", "Blitzcrank", "Nautilus", "Pyke"], correta: 0 },
    { pergunta: "Qual campeã é a sombra de aço?", opcoes: ["Camille", "Fiora", "Katarina", "Evelynn"], correta: 0 },
    { pergunta: "Qual campeã usa poeira estelar e é amiga das estrelas?", opcoes: ["Zoe", "Soraka", "Lux", "Ahri"], correta: 0 },
    { pergunta: "Qual campeão é um guerreiro de gelo que usa dois machados?", opcoes: ["Olaf", "Tryndamere", "Braum", "Udyr"], correta: 0 },
    { pergunta: "Qual campeão é o rei da destruição (Viego)?", opcoes: ["O Rei Destruído", "Mordekaiser", "Aatrox", "Sion"], correta: 0 },
    { pergunta: "Qual o nome da arma da Senna?", opcoes: ["Canhão de Relíquia", "Sussurro", "Besta", "Pistola de Luz"], correta: 0 },
    { pergunta: "Qual campeã usa uma espada de energia e é uma sentinela?", opcoes: ["Gwen", "Riven", "Fiora", "Irelia"], correta: 0 },
    { pergunta: "Qual campeão usa um martelo e é de Piltover?", opcoes: ["Jayce", "Vi", "Ekko", "Viktor"], correta: 0 },
    { pergunta: "Qual campeão é um rato mestre do Kung Fu?", opcoes: ["Kennen", "Twitch", "Master Yi", "Wukong"], correta: 0 },
    { pergunta: "Qual campeão é conhecido como 'A Lâmina do Exílio'?", opcoes: ["Riven", "Yasuo", "Yone", "Aatrox"], correta: 0 },
    { pergunta: "Qual campeã é a tecelã de pedras?", opcoes: ["Taliyah", "Malphite", "Taric", "Rammus"], correta: 0 },
    { pergunta: "Qual campeã é a fúria do deserto?", opcoes: ["Cassiopeia", "Sivir", "Samira", "Morgana"], correta: 1 },
    { pergunta: "Qual campeão usa um escudo de porta?", opcoes: ["Braum", "Leona", "Pantheon", "Taric"], correta: 0 },
    { pergunta: "Qual campeã usa um arco-íris na sua Ultimate?", opcoes: ["Lux", "Zoe", "Seraphine", "Neeko"], correta: 0 },
    { pergunta: "Qual campeão é um viking que entra em Berserk?", opcoes: ["Olaf", "Tryndamere", "Darius", "Garen"], correta: 0 },
    { pergunta: "Qual campeã usa correntes de ferro em cima de um cavalo?", opcoes: ["Rell", "Sejuani", "Quinn", "Samira"], correta: 0 },
    { pergunta: "Qual campeão é o mestre do vazio que cospe ácido?", opcoes: ["Kog'Maw", "Cho'Gath", "Vel'Koz", "Malzahar"], correta: 0 },
    { pergunta: "Qual campeã usa uma flauta (ou instrumento de sopro)?", opcoes: ["Janna", "Sona", "Lulu", "Nami"], correta: 0 },
    { pergunta: "Qual campeã é a mestre das lâminas de Noxus?", opcoes: ["Katarina", "Leblanc", "Samira", "Rell"], correta: 0 },
    { pergunta: "Qual campeão usa uma pá para invocar a Dama?", opcoes: ["Yorick", "Karthus", "Sion", "Thresh"], correta: 0 },
    { pergunta: "Qual campeão é um espantalho assustador?", opcoes: ["Fiddlesticks", "Shaco", "Nocturne", "Hecarim"], correta: 0 },
    { pergunta: "Qual campeão usa uma âncora?", opcoes: ["Nautilus", "Fizz", "Pyke", "Gangplank"], correta: 0 },
    { pergunta: "Qual campeão atira uma rede para fugir?", opcoes: ["Caitlyn", "Jinx", "Graves", "Ashe"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Portal de Reinos'?", opcoes: ["Ryze", "Bardo", "Twisted Fate", "Ekko"], correta: 0 },
    { pergunta: "Qual campeão é um ninja azul que usa shurikens?", opcoes: ["Kennen", "Zed", "Shen", "Akali"], correta: 0 },
    { pergunta: "Qual campeão é o mestre das poções tóxicas?", opcoes: ["Singed", "Twitch", "Mundo", "Viktor"], correta: 0 },
    { pergunta: "Qual campeão é o demónio das sombras?", opcoes: ["Nocturne", "Shaco", "Fiddlesticks", "Zed"], correta: 0 },
    { pergunta: "Qual campeão tem um escudo de pedra?", opcoes: ["Malphite", "Garen", "Rammus", "Skarner"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Chuva de Disparos'?", opcoes: ["Miss Fortune", "Lucian", "Jinx", "Samira"], correta: 0 },
    { pergunta: "Qual campeã é a filha de Kassadin?", opcoes: ["Kai'Sa", "Vayne", "Sivir", "Morgana"], correta: 0 },
    { pergunta: "Qual campeão usa um martelo e salta nos inimigos?", opcoes: ["Poppy", "Jayce", "Ornn", "Braum"], correta: 0 },
    { pergunta: "Qual campeão usa uma serra elétrica?", opcoes: ["Urgot", "Sion", "Dr. Mundo", "Warwick"], correta: 2 },
    { pergunta: "Qual campeão é o mestre do gelo de Freljord?", opcoes: ["Braum", "Olaf", "Anivia", "Nunu"], correta: 2 },
    { pergunta: "Qual campeão é um espadachim de vento?", opcoes: ["Yasuo", "Yone", "Master Yi", "Xin Zhao"], correta: 0 },
    { pergunta: "Qual campeão é o irmão de Yasuo?", opcoes: ["Yone", "Shen", "Zed", "Kayn"], correta: 0 },
    { pergunta: "Qual campeã usa um bumerangue gigante?", opcoes: ["Sivir", "Gnar", "Akshan", "Draven"], correta: 0 },
    { pergunta: "Qual campeã usa um pássaro chamado Valor?", opcoes: ["Quinn", "Anivia", "Ashe", "Kayle"], correta: 0 },
    { pergunta: "Qual campeão tem uma lanterna?", opcoes: ["Thresh", "Jax", "Lulu", "Karma"], correta: 0 },
    { pergunta: "Qual campeão usa um relógio de bolso?", opcoes: ["Ekko", "Zilean", "Ezreal", "Jayce"], correta: 0 },
    { pergunta: "Qual campeão é o imperador das areias?", opcoes: ["Azir", "Nasus", "Renekton", "Xerath"], correta: 0 },
    { pergunta: "Qual campeão é um monstro feito de veneno?", opcoes: ["Zac", "Twitch", "Singed", "Mundo"], correta: 0 },
    { pergunta: "Qual campeão pula e explode inimigos (é de geleia)?", opcoes: ["Zac", "Malphite", "Gragas", "Gnar"], correta: 0 },
    { pergunta: "Qual campeã é a lady dos espinhos?", opcoes: ["Zyra", "Lulu", "Lux", "Ahri"], correta: 0 },
    { pergunta: "Qual campeão é um samurai sem mestre?", opcoes: ["Yasuo", "Yone", "Master Yi", "Xin Zhao"], correta: 0 },
    { pergunta: "Qual campeão usa o fogo para lutar?", opcoes: ["Brand", "Annie", "Ornn", "Shyvana"], correta: 0 },
    { pergunta: "Qual campeã tem uma Ultimate que dá escudo a todos?", opcoes: ["Karma", "Lulu", "Soraka", "Janna"], correta: 0 },
    { pergunta: "Qual campeão usa um tridente?", opcoes: ["Fizz", "Nami", "Nautilus", "Nidalee"], correta: 0 },
    { pergunta: "Qual campeão é o mestre da forja cósmica?", opcoes: ["Aurelion Sol", "Ornn", "Taric", "Bard"], correta: 0 },
    { pergunta: "Qual campeã usa o poder da Lua?", opcoes: ["Diana", "Leona", "Lux", "Soraka"], correta: 0 },
    { pergunta: "Qual campeão usa o poder do Sol?", opcoes: ["Leona", "Diana", "Lux", "Pantheon"], correta: 0 },
    { pergunta: "Qual campeã é uma bailarina de Ionia?", opcoes: ["Irelia", "Akali", "Ahri", "Karma"], correta: 0 },
    { pergunta: "Qual campeão é um Yordle mestre das bombas?", opcoes: ["Ziggs", "Teemo", "Kled", "Tristana"], correta: 0 },
    { pergunta: "Qual campeã usa um tigre (puma) para caçar?", opcoes: ["Nidalee", "Rengar", "Warwick", "Gnar"], correta: 0 },
    { pergunta: "Qual campeão é o rei de Camavor?", opcoes: ["Viego", "Aatrox", "Mordekaiser", "Sion"], correta: 0 },
    { pergunta: "Qual campeão é o protetor de poros?", opcoes: ["Braum", "Olaf", "Nunu", "Gragas"], correta: 0 },
    { pergunta: "Qual campeão é o deus do ferro?", opcoes: ["Mordekaiser", "Taric", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "Qual campeão usa uma capa de lâminas?", opcoes: ["Talon", "Katarina", "Zed", "Kayn"], correta: 0 },
    { pergunta: "Qual campeão usa um lança-chamas?", opcoes: ["Rumble", "Corki", "Brand", "Singed"], correta: 0 },
    { pergunta: "Qual campeão é um ninja de sombras?", opcoes: ["Zed", "Shen", "Akali", "Kennen"], correta: 0 },
    { pergunta: "Qual campeã é a lady do cristal?", opcoes: ["Skarner", "Taric", "Ezreal", "Lux"], correta: 1 },
    { pergunta: "Qual campeão é o mestre do Wuju?", opcoes: ["Master Yi", "Wukong", "Jax", "Yasuo"], correta: 0 },
    { pergunta: "Qual campeã é a rainha do gelo?", opcoes: ["Ashe", "Lissandra", "Sejuani", "Anivia"], correta: 0 },
    { pergunta: "Qual campeão usa um martelo galático?", opcoes: ["Taric", "Jayce", "Poppy", "Ornn"], correta: 0 },
    { pergunta: "Qual campeão é um marinheiro de Bilgewater?", opcoes: ["Gangplank", "Graves", "Pyke", "Nautilus"], correta: 0 },
    { pergunta: "Qual campeã usa uma harpa mágica?", opcoes: ["Sona", "Seraphine", "Nami", "Janna"], correta: 0 },
    { pergunta: "Qual campeão é o mestre das runas?", opcoes: ["Ryze", "Brand", "Xerath", "Malzahar"], correta: 0 },
    { pergunta: "Qual campeão é um gladiador noxiano?", opcoes: ["Draven", "Darius", "Katarina", "Talon"], correta: 0 },
    { pergunta: "Qual campeão usa uma lança?", opcoes: ["Xin Zhao", "Jarvan IV", "Pantheon", "Nidalee"], correta: 0 },
    { pergunta: "Qual campeão é o príncipe de Demacia?", opcoes: ["Jarvan IV", "Garen", "Lux", "Galio"], correta: 0 },
    { pergunta: "Qual campeão é o deus da guerra?", opcoes: ["Pantheon", "Aatrox", "Tryndamere", "Darius"], correta: 0 },
    { pergunta: "Qual campeão usa o tempo a seu favor?", opcoes: ["Zilean", "Ekko", "Lucian", "Ryze"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Destino'?", opcoes: ["Twisted Fate", "Bardo", "Ryze", "Pantheon"], correta: 0 },
    { pergunta: "Qual campeão é um escorpião?", opcoes: ["Skarner", "Rammus", "Malphite", "Anivia"], correta: 0 },
    { pergunta: "Qual campeão usa veneno no seu sopro?", opcoes: ["Kog'Maw", "Twitch", "Singed", "Teemo"], correta: 0 },
    { pergunta: "Qual campeão é um boneco de palha?", opcoes: ["Fiddlesticks", "Shaco", "Nocturne", "Pyke"], correta: 0 },
    { pergunta: "Qual campeão é o colecionador de almas?", opcoes: ["Thresh", "Senna", "Lucian", "Yorick"], correta: 0 },
    { pergunta: "Qual campeão usa a passiva 'Explosão de Cristal'?", opcoes: ["Skarner", "Taric", "Malphite", "Lux"], correta: 0 },
    { pergunta: "Qual campeão é um Yordle que pilota um helicóptero?", opcoes: ["Corki", "Rumble", "Ziggs", "Heimerdinger"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Barragem Incendiária'?", opcoes: ["Corki", "Ezreal", "Gangplank", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeão é conhecido como 'O Grandioso Vigilante'?", opcoes: ["Vel'Koz", "Malzahar", "Kassadin", "Cho'Gath"], correta: 0 },
    { pergunta: "Qual campeão é o 'Andarilho Espiritual'?", opcoes: ["Udyr", "Lee Sin", "Master Yi", "Wukong"], correta: 0 },
    { pergunta: "Qual campeã usa uma técnica chamada 'Dança das Lâminas'?", opcoes: ["Irelia", "Fiora", "Katarina", "Akali"], correta: 0 },
    { pergunta: "Qual campeã é a 'Matriarca de Guerra' de Freljord?", opcoes: ["Ashe", "Sejuani", "Lissandra", "Sivir"], correta: 1 },
    { pergunta: "Qual campeão usa a habilidade 'Carga Devastadora'?", opcoes: ["Hecarim", "Sion", "Rammus", "Darius"], correta: 0 },
    { pergunta: "Qual campeã tem a passiva 'Vingança Incandescente'?", opcoes: ["Annie", "Brand", "Shyvana", "Zyra"], correta: 0 },
    { pergunta: "Qual campeão é o 'Guardião das Areias'?", opcoes: ["Nasus", "Azir", "Rammus", "Skarner"], correta: 2 },
    { pergunta: "Qual campeão tem a Ultimate 'Abalo Terrestre'?", opcoes: ["Malphite", "Rammus", "Alistar", "Galio"], correta: 1 },
    { pergunta: "Qual campeão é o 'Minotauro'?", opcoes: ["Alistar", "Braum", "Malphite", "Sion"], correta: 0 },
    { pergunta: "Qual campeã é a 'Fúria da Tormenta'?", opcoes: ["Janna", "Anivia", "Karma", "Lux"], correta: 0 },
    { pergunta: "Qual campeã usa a habilidade 'Olhar Petrificante'?", opcoes: ["Cassiopeia", "Morgana", "Zyra", "Lissandra"], correta: 0 },
    { pergunta: "Qual campeão é o 'Ladrão de Almas'?", opcoes: ["Thresh", "Vladimir", "Karthus", "Veigar"], correta: 1 },
    { pergunta: "Qual campeão é o 'Mago Maligno'?", opcoes: ["Veigar", "Ryze", "Brand", "Karthus"], correta: 0 },
    { pergunta: "Qual campeã é a 'Lâmina Sinistra'?", opcoes: ["Katarina", "Akali", "Diana", "Samira"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Dano Colateral'?", opcoes: ["Graves", "Jinx", "Tristana", "Lucian"], correta: 0 },
    { pergunta: "Qual campeã usa 'Luz Estelar' para curar?", opcoes: ["Soraka", "Taric", "Sona", "Lulu"], correta: 1 },
    { pergunta: "Qual campeão é o 'Despercebido'?", opcoes: ["Twitch", "Shaco", "Evelynn", "Rengar"], correta: 0 },
    { pergunta: "Qual campeão é o 'Coração de Ferro'?", opcoes: ["Blitzcrank", "Mordekaiser", "Viktor", "Urgot"], correta: 0 },
    { pergunta: "Qual campeã é a 'Arqueira de Cristal'?", opcoes: ["Ashe", "Sejuani", "Sivir", "Quinn"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Golpe de Misericórdia'?", opcoes: ["Garen", "Darius", "Pyke", "Urgot"], correta: 1 },
    { pergunta: "Qual campeão é o 'Mestre do Metal'?", opcoes: ["Mordekaiser", "Rell", "Taric", "Skarner"], correta: 0 },
    { pergunta: "Qual campeã é a 'Vingadora de Ionia'?", opcoes: ["Irelia", "Akali", "Karma", "Ahri"], correta: 0 },
    { pergunta: "Qual campeã tem a habilidade 'Encanto' (Sedução)?", opcoes: ["Ahri", "Evelynn", "Seraphine", "Zoe"], correta: 0 },
    { pergunta: "Qual campeã usa 'Poeira de Estrela'?", opcoes: ["Zoe", "Soraka", "Lux", "Janna"], correta: 0 },
    { pergunta: "Qual campeão é o 'Yordle de Ferro'?", opcoes: ["Poppy", "Rumble", "Kled", "Tristana"], correta: 0 },
    { pergunta: "Qual campeã usa 'Tiros de Fogo' de um dragão?", opcoes: ["Shyvana", "Annie", "Tristana", "Vex"], correta: 2 },
    { pergunta: "Qual campeão tem a Ultimate 'Cataclismo'?", opcoes: ["Jarvan IV", "Malphite", "Sion", "Galio"], correta: 0 },
    { pergunta: "Qual campeão é o 'Exilado de Ionia'?", opcoes: ["Yasuo", "Yone", "Zed", "Kayn"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Muralha de Vento'?", opcoes: ["Yasuo", "Yone", "Braum", "Samira"], correta: 0 },
    { pergunta: "Qual campeão é o 'Ceifador das Sombras'?", opcoes: ["Kayn", "Zed", "Karthus", "Thresh"], correta: 0 },
    { pergunta: "Qual o nome da foice do Kayn?", opcoes: ["Rhaast", "Sussurro", "Darkin", "Lâmina"], correta: 0 },
    { pergunta: "Qual campeã é a 'Rosa Negra'?", opcoes: ["LeBlanc", "Morgana", "Evelynn", "Zyra"], correta: 0 },
    { pergunta: "Qual campeã é a 'Imperatriz do Vazio'?", opcoes: ["Bel'Veth", "Rek'Sai", "Kai'Sa", "Zyra"], correta: 0 },
    { pergunta: "Qual campeã usa a habilidade 'Chuva Icathiana'?", opcoes: ["Kai'Sa", "Vayne", "Ashe", "Sivir"], correta: 0 },
    { pergunta: "Qual campeã é a 'Mestra das Lâminas Flutuantes'?", opcoes: ["Irelia", "Katarina", "Akali", "Fiora"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Gancho de Corrente'?", opcoes: ["Thresh", "Sylas", "Nautilus", "Blitzcrank"], correta: 1 },
    { pergunta: "Qual campeã é a 'Artilheira Relâmpago'?", opcoes: ["Zeri", "Jinx", "Tristana", "Sivir"], correta: 0 },
    { pergunta: "Qual campeã usa 'Ritmos' para lutar?", opcoes: ["Seraphine", "Sona", "Nami", "Janna"], correta: 0 },
    { pergunta: "Qual campeã é a 'Cantora Estelar'?", opcoes: ["Seraphine", "Sona", "Lux", "Ahri"], correta: 0 },
    { pergunta: "Qual campeão é o 'Terror de Zaun'?", opcoes: ["Warwick", "Singed", "Urgot", "Dr. Mundo"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Frenesi Sanguinário'?", opcoes: ["Warwick", "Olaf", "Tryndamere", "Renekton"], correta: 0 },
    { pergunta: "Qual campeão usa 'Veneno de Rato'?", opcoes: ["Twitch", "Singed", "Teemo", "Cassiopeia"], correta: 0 },
    { pergunta: "Qual campeão tem a habilidade 'Embosca'?", opcoes: ["Twitch", "Shaco", "Rengar", "Kha'Zix"], correta: 0 },
    { pergunta: "Qual campeã é a 'Lâmina do Zelo'?", opcoes: ["Irelia", "Akali", "Fiora", "Sivir"], correta: 0 },
    { pergunta: "Qual campeã usa a habilidade 'Passo Sombrio'?", opcoes: ["Akali", "Kayn", "Zed", "Katarina"], correta: 1 },
    { pergunta: "Qual campeão usa 'Barris de Pólvora'?", opcoes: ["Gangplank", "Gragas", "Ziggs", "Corki"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Julgamento' (Rodopiar)?", opcoes: ["Garen", "Wukong", "Darius", "Jax"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Decisivo' no Q?", opcoes: ["Garen", "Darius", "Jax", "Sion"], correta: 0 },
    { pergunta: "Qual campeão é o 'General de Noxus'?", opcoes: ["Swain", "Darius", "Draven", "Kled"], correta: 0 },
    { pergunta: "Qual campeão tem 'Pássaros' de estimação (Beatrix)?", opcoes: ["Swain", "Quinn", "Fiddlesticks", "Anivia"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Mão da Morte'?", opcoes: ["Swain", "Darius", "Sion", "Karthus"], correta: 0 },
    { pergunta: "Qual campeão é o 'Carrasco de Noxus'?", opcoes: ["Draven", "Darius", "Urgot", "Talon"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'League of Draven'?", opcoes: ["Draven", "Darius", "Swain", "Kled"], correta: 0 },
    { pergunta: "Qual campeão é o 'Grande Cavalariço'?", opcoes: ["Kled", "Hecarim", "Sejuani", "Rell"], correta: 0 },
    { pergunta: "Qual o nome do lagarto do Kled?", opcoes: ["Skaarl", "Tibbers", "Daisy", "Willump"], correta: 0 },
    { pergunta: "Qual campeão é o 'Pastor de Almas'?", opcoes: ["Yorick", "Thresh", "Karthus", "Sion"], correta: 0 },
    { pergunta: "Qual o nome da entidade que o Yorick invoca?", opcoes: ["Dama da Névoa", "Daisy", "Tibbers", "Skaarl"], correta: 0 },
    { pergunta: "Qual campeão é o 'Monstro das Poças'?", opcoes: ["Zac", "Gragas", "Tahm Kench", "Fizz"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Divisão Celular'?", opcoes: ["Zac", "Anivia", "Aatrox", "Sion"], correta: 0 },
    { pergunta: "Qual campeã é a 'Luz de Ionia'?", opcoes: ["Karma", "Lux", "Ahri", "Irelia"], correta: 0 },
    { pergunta: "Qual campeã usa a habilidade 'Mantra'?", opcoes: ["Karma", "Lulu", "Lux", "Ahri"], correta: 0 },
    { pergunta: "Qual campeão é o 'Olho do Crepúsculo'?", opcoes: ["Shen", "Kennen", "Zed", "Akali"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Corrida das Sombras'?", opcoes: ["Shen", "Zed", "Akali", "Kayn"], correta: 0 },
    { pergunta: "Qual campeão é o 'Mestre das Sombras'?", opcoes: ["Zed", "Shen", "Akali", "Kennen"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Marca da Morte'?", opcoes: ["Zed", "Katarina", "Kayn", "Talon"], correta: 0 },
    { pergunta: "Qual campeão é a 'Voz do Vazio'?", opcoes: ["Malzahar", "Kassadin", "Vel'Koz", "Kog'Maw"], correta: 0 },
    { pergunta: "Qual campeão usa 'Zonas de Silêncio'?", opcoes: ["Malzahar", "Kassadin", "Cho'Gath", "Garen"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Aperto do Infinito'?", opcoes: ["Malzahar", "Warwick", "Skarner", "Vi"], correta: 0 },
    { pergunta: "Qual campeão é o 'Andarilho do Vazio'?", opcoes: ["Kassadin", "Malzahar", "Vel'Koz", "Kha'Zix"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Lâmina Ínfera'?", opcoes: ["Kassadin", "Master Yi", "Yasuo", "Aatrox"], correta: 0 },
    { pergunta: "Qual campeão é o 'Terror do Vazio'?", opcoes: ["Cho'Gath", "Kog'Maw", "Vel'Koz", "Rek'Sai"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Banquete'?", opcoes: ["Cho'Gath", "Tahm Kench", "Nunu", "Gnar"], correta: 0 },
    { pergunta: "Qual campeão é o 'Ceifador do Vazio'?", opcoes: ["Kha'Zix", "Rengar", "Vel'Koz", "Kog'Maw"], correta: 0 },
    { pergunta: "Qual campeão tem a habilidade 'Sabor de Medo'?", opcoes: ["Kha'Zix", "Nocturne", "Fiddlesticks", "Shaco"], correta: 0 },
    { pergunta: "Qual campeão é o 'Olho do Vazio'?", opcoes: ["Vel'Koz", "Malzahar", "Kog'Maw", "Kassadin"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Raios Desintegradores'?", opcoes: ["Vel'Koz", "Lux", "Xerath", "Viktor"], correta: 0 },
    { pergunta: "Qual campeão é a 'Boca do Abismo'?", opcoes: ["Kog'Maw", "Cho'Gath", "Tahm Kench", "Urgot"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Surpresa Icathiana' (Explodir ao morrer)?", opcoes: ["Kog'Maw", "Sion", "Zac", "Anivia"], correta: 0 },
    { pergunta: "Qual campeão é o 'Escavador do Vazio'?", opcoes: ["Rek'Sai", "Skarner", "Cho'Gath", "Malphite"], correta: 0 },
    { pergunta: "Qual campeã usa 'Túneis' para se mover?", opcoes: ["Rek'Sai", "Bard", "Thresh", "Lulu"], correta: 0 },
    { pergunta: "Qual campeão é o 'Guerreiro Eterno'?", opcoes: ["Sion", "Aatrox", "Tryndamere", "Garen"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Investida Incontrolável'?", opcoes: ["Sion", "Hecarim", "Rammus", "Malphite"], correta: 0 },
    { pergunta: "Qual campeão é a 'Sentinela do Medo'?", opcoes: ["Fiddlesticks", "Nocturne", "Shaco", "Nocturne"], correta: 0 },
    { pergunta: "Qual o nome da foice do Fiddlesticks?", opcoes: ["Não tem nome", "Sussurro", "Rhaast", "Foice do Medo"], correta: 0 },
    { pergunta: "Qual campeão é o 'Eterno Pesadelo'?", opcoes: ["Nocturne", "Shaco", "Fiddlesticks", "Zed"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Paranoia' (Escurecer o mapa)?", opcoes: ["Nocturne", "Twisted Fate", "Rengar", "Kha'Zix"], correta: 0 },
    { pergunta: "Qual campeão é o 'Bufão Demoníaco'?", opcoes: ["Shaco", "Fiddlesticks", "Ziggs", "Kled"], correta: 0 },
    { pergunta: "Qual campeão usa 'Caixinhas Surpresa'?", opcoes: ["Shaco", "Jinx", "Teemo", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeão é a 'Lança da Vingança'?", opcoes: ["Kalista", "Xin Zhao", "Pantheon", "Nidalee"], correta: 0 },
    { pergunta: "Qual campeã faz um 'Juramento' com um aliado?", opcoes: ["Kalista", "Taric", "Yuumi", "Lulu"], correta: 0 },
    { pergunta: "Qual campeã usa 'Lanças de Alma'?", opcoes: ["Kalista", "Nidalee", "Ashe", "Senna"], correta: 0 },
    { pergunta: "Qual campeão é o 'Rei das Pulgas' (brincadeira) ou 'Yordle Saltador'?", opcoes: ["Gnar", "Teemo", "Kled", "Fizz"], correta: 0 },
    { pergunta: "Qual o nome do bumerangue do Gnar?", opcoes: ["Bumerangue", "Skaarl", "Sussurro", "Boomer"], correta: 0 },
    { pergunta: "Qual campeão é o 'Mestre da Montanha'?", opcoes: ["Ornn", "Malphite", "Braum", "Taric"], correta: 0 },
    { pergunta: "Qual o nome do bode que o Ornn invoca?", opcoes: ["Chamado do Deus da Forja", "Daisy", "Tibbers", "Bode"], correta: 0 },
    { pergunta: "Qual campeão é o 'Protetor de Ionia'?", opcoes: ["Ivern", "Shen", "Karma", "Lee Sin"], correta: 0 },
    { pergunta: "Qual o nome do golem da margarida que o Ivern invoca?", opcoes: ["Margarida (Daisy)", "Tibbers", "Skaarl", "Willump"], correta: 0 },
    { pergunta: "Qual item concede um escudo de feitiço passivo para Magos?", opcoes: ["Véu da Banshee", "Zhonya", "Rabadon", "Morello"], correta: 0 },
    { pergunta: "Qual item aumenta drasticamente o Poder de Habilidade total?", opcoes: ["Capuz da Morte de Rabadon", "Eco de Luden", "Cajado do Vazio", "Liandry"], correta: 0 },
    { pergunta: "Qual item é usado para reviver o campeão após a morte?", opcoes: ["Anjo Guardião", "Sinal de Sterak", "Sedenta por Sangue", "Passos de Mercúrio"], correta: 0 },
    { pergunta: "Qual item de suporte permite colocar sentinelas?", opcoes: ["Item de Suporte evoluído", "Poção Corrupta", "Anel de Doran", "Lâmina de Doran"], correta: 0 },
    { pergunta: "Qual item é focado em dar Dano Verdadeiro contra Tanques?", opcoes: ["Mata-Cráquens", "Gume do Infinito", "Dançarina Fantasma", "Furacão de Runaan"], correta: 0 },
    { pergunta: "Qual bota concede Velocidade de Ataque?", opcoes: ["Grevas do Berserker", "Botas da Mobilidade", "Passos de Mercúrio", "Botas Galvanizadas"], correta: 0 },
    { pergunta: "Qual bota é melhor contra times com muito Controle de Grupo (CC)?", opcoes: ["Passos de Mercúrio", "Botas da Rapidez", "Grevas do Berserker", "Sapatos do Feiticeiro"], correta: 0 },
    { pergunta: "Qual item cria uma área que cura aliados?", opcoes: ["Redenção", "Turíbulo Ardente", "Mandato Imperial", "Hino Bélico"], correta: 0 },
    { pergunta: "Qual item permite que Atiradores causem dano em área?", opcoes: ["Furacão de Runaan", "Canhão Fumegante", "Chuva de Canivete", "Punhal Serrilhado"], correta: 0 },
    { pergunta: "Qual item corta a cura dos inimigos (Feridas Graves) para magos?", opcoes: ["Morellonomicon", "Lembrete Mortal", "Sinal de Sterak", "Cutelo Negro"], correta: 0 },
    { pergunta: "Qual item de Tanque queima inimigos próximos?", opcoes: ["Égide de Fogo Solar", "Armadura de Espinhos", "Coração Congelado", "Semblante Espiritual"], correta: 0 },
    { pergunta: "Qual item devolve dano físico aos atacantes?", opcoes: ["Armadura de Espinhos", "Presságio de Randuin", "Couraça do Defunto", "Coração de Aço"], correta: 0 },
    { pergunta: "Qual item aumenta o alcance do próximo ataque básico?", opcoes: ["Canhão Fumegante", "Dançarina Fantasma", "Gume do Infinito", "Colhedor de Essência"], correta: 0 },
    { pergunta: "Qual item é essencial para o Ezreal ter Mana e Dano?", opcoes: ["Colhedor de Essência", "Muramana", "Cajado do Arcanjo", "Lança de Shojin"], correta: 1 },
    { pergunta: "Qual o nome do item que remove efeitos de controle do seu aliado?", opcoes: ["Benção de Mikael", "Redenção", "Turíbulo Ardente", "Solari"], correta: 0 },
    { pergunta: "Qual item de suporte dá um escudo em área para o time?", opcoes: ["Medalhão dos Solari de Ferro", "Redenção", "Mikael", "Juramento do Cavaleiro"], correta: 0 },
    { pergunta: "Qual item concede Velocidade de Movimento ao caminhar?", opcoes: ["Couraça do Defunto", "Armadura de Espinhos", "Coração Congelado", "Força da Natureza"], correta: 0 },
    { pergunta: "Qual item dá Resistência Mágica e cura aumentada?", opcoes: ["Semblante Espiritual", "Véu da Banshee", "Fim da Noite", "Mandíbula de Malmortius"], correta: 0 },
    { pergunta: "Qual item de assassino concede invisibilidade após um abate?", opcoes: ["Crepúsculo de Draktharr", "Garra do Espreitador", "Lâmina Fantasma de Youmuu", "Limiar da Noite"], correta: 0 },
    { pergunta: "Qual item permite atravessar paredes (ativo)?", opcoes: ["Lâmina Fantasma de Youmuu", "Garra do Espreitador", "Passos de Mercúrio", "Nenhum"], correta: 3 },
    { pergunta: "Qual monstro do rio concede ouro para todo o time ao morrer?", opcoes: ["Dragão", "Barão Nashor", "Arauto", "Todos acima"], correta: 3 },
    { pergunta: "Quantos Dragões Elementais um time precisa para pegar a Alma?", opcoes: ["2", "3", "4", "5"], correta: 2 },
    { pergunta: "Qual Arauto do Vale você pode 'dirigir' contra torres?", opcoes: ["O Primeiro", "O Segundo", "O Terceiro", "Nenhum"], correta: 1 },
    { pergunta: "Qual o tempo de ressurgimento do Barão Nashor após ser morto?", opcoes: ["5 minutos", "6 minutos", "7 minutos", "8 minutos"], correta: 1 },
    { pergunta: "Qual o tempo de ressurgimento do Dragão?", opcoes: ["5 minutos", "6 minutos", "7 minutos", "4 minutos"], correta: 0 },
    { pergunta: "Qual planta explode e joga campeões para longe?", opcoes: ["Frutamel", "Pome de Estouro", "Flor Vidente", "Pinha Explosiva"], correta: 3 },
    { pergunta: "Qual planta revela inimigos e sentinelas no mapa?", opcoes: ["Flor Vidente", "Pinha Explosiva", "Frutamel", "Lótus"], correta: 0 },
    { pergunta: "Qual planta recupera vida e mana?", opcoes: ["Frutamel", "Flor Vidente", "Pinha Explosiva", "Cogumelo"], correta: 0 },
    { pergunta: "Qual campeão é conhecido como o 'Mestre da Montanha'?", opcoes: ["Ornn", "Malphite", "Taliyah", "Taric"], correta: 1 },
    { pergunta: "Qual campeão usa a passiva 'Iluminação'?", opcoes: ["Lux", "Morgana", "Karma", "Lulu"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Chuva de Flechas'?", opcoes: ["Varus", "Ashe", "Quinn", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão é um demônio que come segredos?", opcoes: ["Fiddlesticks", "Nocturne", "Tahm Kench", "Evelynn"], correta: 0 },
    { pergunta: "Qual campeã tem a passiva 'Pés Ligeiros'?", opcoes: ["Sivir", "Vayne", "Kai'Sa", "Ashe"], correta: 0 },
    { pergunta: "Qual campeão é o 'Pastor de Almas'?", opcoes: ["Yorick", "Thresh", "Senna", "Karthus"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Lâmina Zenit'?", opcoes: ["Leona", "Diana", "Lux", "Taric"], correta: 0 },
    { pergunta: "Qual campeã tem a habilidade 'Proteção de Ionia'?", opcoes: ["Irelia", "Karma", "Akali", "Ahri"], correta: 1 },
    { pergunta: "Qual campeã é a 'Lança da Vingança'?", opcoes: ["Kalista", "Nidalee", "Ashe", "Vayne"], correta: 0 },
    { pergunta: "Qual campeão é o 'Escultor de Vidro'?", opcoes: ["Hwei", "Jhin", "Ezreal", "Jayce"], correta: 0 },
    { pergunta: "Qual campeão usa 'Tinta' para lutar?", opcoes: ["Hwei", "Kayn", "Zed", "Akali"], correta: 0 },
    { pergunta: "Qual campeão é um pequeno dragão de fogo?", opcoes: ["Smolder", "Aurelion Sol", "Shyvana", "Brand"], correta: 0 },
    { pergunta: "Qual campeã é a 'Rosa Negra'?", opcoes: ["LeBlanc", "Cassiopeia", "Elise", "Morgana"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Mergulho Abissal'?", opcoes: ["Rek'Sai", "Nautilus", "Fizz", "Pyke"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Eternidade'?", opcoes: ["Ryze", "Kassadin", "Anivia", "Zilean"], correta: 0 },
    { pergunta: "Qual campeã tem a Ultimate 'Onda Crescente'?", opcoes: ["Nami", "Sona", "Seraphine", "Janna"], correta: 0 },
    { pergunta: "Qual campeão é o 'Guerreiro da Lança'?", opcoes: ["Xin Zhao", "Jarvan IV", "Pantheon", "Jax"], correta: 0 },
    { pergunta: "Qual campeão tem a habilidade 'Contra-Ataque'?", opcoes: ["Jax", "Fiora", "Garen", "Darius"], correta: 0 },
    { pergunta: "Qual campeão é o 'Mestre da Selva' (Leão)?", opcoes: ["Rengar", "Kha'Zix", "Nidalee", "Warwick"], correta: 0 },
    { pergunta: "Qual campeão é o 'Lutador Embriagado'?", opcoes: ["Gragas", "Bardo", "Jax", "Olaf"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Adrenalina'?", opcoes: ["Dr. Mundo", "Olaf", "Tryndamere", "Garen"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Vazio Imundo'?", opcoes: ["Kog'Maw", "Cho'Gath", "Malzahar", "Kassadin"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Carapaça Adaptativa'?", opcoes: ["Kha'Zix", "Rek'Sai", "Skarner", "Cho'Gath"], correta: 3 },
    { pergunta: "Qual campeão usa a habilidade 'Corte de Vento'?", opcoes: ["Riven", "Yasuo", "Yone", "Master Yi"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Impacto Meteoro'?", opcoes: ["Pantheon", "Galio", "Malphite", "Sion"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Lança de Longo Alcance'?", opcoes: ["Nidalee", "Xin Zhao", "Jarvan IV", "Pantheon"], correta: 0 },
    { pergunta: "Qual campeã tem a Ultimate 'Desafio Grandioso'?", opcoes: ["Fiora", "Irelia", "Camille", "Riven"], correta: 0 },
    { pergunta: "Qual campeã usa 'Lâminas de Rapidez'?", opcoes: ["Sivir", "Katarina", "Akali", "Vayne"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Derrubar'?", opcoes: ["Jarvan IV", "Garen", "Darius", "Sion"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Estandarte Demaciano'?", opcoes: ["Jarvan IV", "Garen", "Xin Zhao", "Galio"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Explosão Primordial'?", opcoes: ["Veigar", "Ryze", "Brand", "Karthus"], correta: 0 },
    { pergunta: "Qual campeão é o 'Senhor do Trovão'?", opcoes: ["Volibear", "Kennen", "Ornn", "Janna"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Grito de Guerra'?", opcoes: ["Xin Zhao", "Darius", "Garen", "Olaf"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Garra do Dragão'?", opcoes: ["Shyvana", "Jarvan IV", "Lee Sin", "Aurelion Sol"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Rugido do Trovão'?", opcoes: ["Volibear", "Rengar", "Warwick", "Udyr"], correta: 0 },
    { pergunta: "Qual campeã tem a passiva 'Sede de Sangue'?", opcoes: ["Briar", "Warwick", "Vladimir", "Evelynn"], correta: 0 },
    { pergunta: "Qual campeã usa a habilidade 'Prensagem Hidráulica'?", opcoes: ["Camille", "Vi", "Caitlyn", "Jinx"], correta: 0 },
    { pergunta: "Qual campeã tem a Ultimate 'Ultimato Hextec'?", opcoes: ["Camille", "Jayce", "Viktor", "Ekko"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Cápsula do Tempo'?", opcoes: ["Zilean", "Ekko", "Lucian", "Ryze"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Amizade' com a selva?", opcoes: ["Ivern", "Maokai", "Nunu", "Fiddlesticks"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Mão do Gancho'?", opcoes: ["Blitzcrank", "Thresh", "Nautilus", "Pyke"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Campo Estático'?", opcoes: ["Blitzcrank", "Viktor", "Kennen", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeã tem a passiva 'Pilha de Sucata'?", opcoes: ["Rumble", "Blitzcrank", "Heimerdinger", "Corki"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Equilíbrio'?", opcoes: ["Kennen", "Zed", "Akali", "Shen"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Determinação'?", opcoes: ["Garen", "Darius", "Sion", "Jarvan IV"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Impacto de Iclathia'?", opcoes: ["Kai'Sa", "Kassadin", "Malzahar", "Kog'Maw"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Monção'?", opcoes: ["Janna", "Nami", "Sona", "Lulu"], correta: 0 },
    { pergunta: "Qual campeão é o 'Sentinela do Vazio'?", opcoes: ["Kassadin", "Malzahar", "Vel'Koz", "Kha'Zix"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Lâmina Estelar'?", opcoes: ["Taric", "Ezreal", "Leona", "Diana"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Vibração'?", opcoes: ["Skarner", "Rammus", "Malphite", "Blitzcrank"], correta: 0 },
    { pergunta: "Qual campeã usa a habilidade 'Passo de Vento'?", opcoes: ["Janna", "Yasuo", "Yone", "Taliyah"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Abalo Terrestre'?", opcoes: ["Rammus", "Malphite", "Garen", "Sion"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Bola de Poder'?", opcoes: ["Rammus", "Nunu", "Ziggs", "Gragas"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Pele Dura'?", opcoes: ["Rammus", "Malphite", "Alistar", "Braum"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Provocação Lancinante'?", opcoes: ["Rammus", "Shen", "Galio", "Alistar"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Tremor'?", opcoes: ["Rammus", "Malphite", "Sion", "Galio"], correta: 0 },
    { pergunta: "Qual campeão é o 'Rei das Areias' (Tatuzinho)?", opcoes: ["Rammus", "Azir", "Nasus", "Renekton"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Defesa Curvada'?", opcoes: ["Rammus", "Malphite", "Braum", "Leona"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Armadura de Espinhos' natural?", opcoes: ["Rammus", "Malphite", "Sion", "Garen"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Impacto Meteoro'?", opcoes: ["Pantheon", "Galio", "Sion", "Malphite"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Grande Estrela'?", opcoes: ["Aurelion Sol", "Taric", "Soraka", "Bard"], correta: 0 },
    { pergunta: "Qual campeã tem a passiva 'Beijo da Morte'?", opcoes: ["Evelynn", "Ahri", "Morgana", "Leblanc"], correta: 0 },
    { pergunta: "Qual campeã usa a habilidade 'Espinhos de Ódio'?", opcoes: ["Evelynn", "Zyra", "Elise", "Morgana"], correta: 0 },
    { pergunta: "Qual campeã tem a Ultimate 'Último Carinho'?", opcoes: ["Evelynn", "Ahri", "Miss Fortune", "Jinx"], correta: 0 },
    { pergunta: "Qual campeão tem a passiva 'Encantar'?", opcoes: ["Rakan", "Ahri", "Evelynn", "Seraphine"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Entrada Triunfal'?", opcoes: ["Rakan", "Alistar", "Malphite", "Jarvan IV"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'A Dança das Sombras'?", opcoes: ["Akali", "Zed", "Kayn", "Talon"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Corte Crescente'?", opcoes: ["Akali", "Katarina", "Diana", "Yasuo"], correta: 0 },
    { pergunta: "Qual campeã tem a passiva 'Disciplina Gêmea'?", opcoes: ["Akali", "Irelia", "Karma", "Lux"], correta: 0 },
    { pergunta: "Qual campeão usa a habilidade 'Proteção do Crepúsculo'?", opcoes: ["Shen", "Akali", "Zed", "Kennen"], correta: 1 },
    { pergunta: "Qual campeão tem a Ultimate 'Manto das Sombras'?", opcoes: ["Akali", "Evelynn", "Twitch", "Shaco"], correta: 0 },
    { pergunta: "Qual campeão é o 'Mestre da Lâmina de Ionia'?", opcoes: ["Irelia", "Yasuo", "Master Yi", "Yone"], correta: 0 }
];
