export const bancoPerguntas = [
    { pergunta: "Qual campeão possui a Ultimate 'Caminho do Herói'?", opcoes: ["K'Sante", "Jax", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Aatrox, o Exterminador de Mundos'?", opcoes: ["Aatrox", "Tryndamere", "Renekton", "Nasus"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Chuva de Balas'?", opcoes: ["Miss Fortune", "Lucian", "Samira", "Jinx"], correta: 0 },
    { pergunta: "Qual campeã tem a Ultimate 'Lótus da Morte'?", opcoes: ["Katarina", "Samira", "Akali", "Fiora"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Poder de Demacia'?", opcoes: ["Garen", "Jarvan IV", "Xin Zhao", "Lux"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Crescimento Gigante'?", opcoes: ["Lulu", "Cho'Gath", "Zac", "Malphite"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Requiem'?", opcoes: ["Karthus", "Yorick", "Mordekaiser", "Thresh"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Ragnarok'?", opcoes: ["Olaf", "Tryndamere", "Volibear", "Udyr"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Destino'?", opcoes: ["Twisted Fate", "Ekko", "Ryze", "Bardo"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Luz Final'?", opcoes: ["Lux", "Morgana", "Seraphine", "Senna"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Grande Entrada'?", opcoes: ["Rakan", "Alistar", "Braum", "Sett"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Infernun'?", opcoes: ["Aphelios", "Brand", "Annie", "Xerath"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Encanto'?", opcoes: ["Ahri", "Evelynn", "Seraphine", "Sona"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Grito Primordial'?", opcoes: ["Gnar", "Renekton", "Cho'Gath", "Warwick"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'A Prisão de Cordas'?", opcoes: ["Amumu", "Sejuani", "Leona", "Skarner"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Flecha de Cristal Encantada'?", opcoes: ["Ashe", "Varus", "Vayne", "Quinn"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'O Chamado do Destino'?", opcoes: ["Kalista", "Thresh", "Lucian", "Viego"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Soco de Alavanca'?", opcoes: ["Vi", "Sett", "Lee Sin", "Blitzcrank"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Cataclismo'?", opcoes: ["Jarvan IV", "Malphite", "Taliyah", "Yorick"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Barril de Pólvora' (Mega)?", opcoes: ["Gragas", "Gangplank", "Ziggs", "Corki"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Chacina'?", opcoes: ["Renekton", "Darius", "Nasus", "Aatrox"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Grande Desafio'?", opcoes: ["Fiora", "Irelia", "Camille", "Riven"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'O Chamado do Deus da Forja'?", opcoes: ["Ornn", "Volibear", "Anivia", "Braum"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Campo Amortecedor'?", opcoes: ["Orianna", "Viktor", "Lulu", "Yuumi"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Último Suspiro'?", opcoes: ["Yasuo", "Yone", "Master Yi", "Xin Zhao"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Domínio das Sombras'?", opcoes: ["Zed", "Kayn", "Talon", "Nocturne"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Sentença de Morte' (Cárcere)?", opcoes: ["Thresh", "Nautilus", "Blitzcrank", "Pyke"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Monção'?", opcoes: ["Janna", "Soraka", "Nami", "Lulu"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Divisor de Marés'?", opcoes: ["Nami", "Fizz", "Nautilus", "Pyke"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Lâmina do Exílio'?", opcoes: ["Riven", "Fiora", "Aatrox", "Yasuo"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Abraço da Agonia'?", opcoes: ["Evelynn", "Morgana", "Ahri", "Leblanc"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Paraíso'?", opcoes: ["Shen", "Soraka", "Karthus", "Galio"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Crescendo'?", opcoes: ["Sona", "Seraphine", "Bardo", "Rakan"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Frenesi Sanguinário'?", opcoes: ["Warwick", "Briar", "Vladimir", "Rengar"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'A Face da Montanha' (Força da Natureza)?", opcoes: ["Malphite", "Maokai", "Ornn", "Galio"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Vassoura de Aço' (Varredura)?", opcoes: ["Camille", "Fiora", "Vi", "Irelia"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Beijo da Morte'?", opcoes: ["Vayne", "Evelynn", "Caitlyn", "Sivir"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Tempestade de Corvos'?", opcoes: ["Fiddlesticks", "Swain", "Nocturne", "Anivia"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Grande Estrela Cadente'?", opcoes: ["Pantheon", "Galio", "Aurelion Sol", "Leona"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Lâminas de Lótus' (Vanguarda)?", opcoes: ["Irelia", "Akali", "Katarina", "Samira"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Morte vinda de Baixo'?", opcoes: ["Pyke", "Nautilus", "Fizz", "Urgot"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Ponto de Ruptura'?", opcoes: ["Rell", "Leona", "Taric", "Alistar"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Destino Selado'?", opcoes: ["Yone", "Yasuo", "Zed", "Shen"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'O Show Deve Continuar'?", opcoes: ["Sett", "Vi", "Lee Sin", "Braum"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Auge do Poder'?", opcoes: ["Syndra", "Xerath", "Veigar", "Lux"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Massacre'?", opcoes: ["Aatrox", "Master Yi", "Olaf", "Renekton"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Abraço da Agonia'?", opcoes: ["Morgana", "Evelynn", "Leblanc", "Zyra"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Impacto Meteoro'?", opcoes: ["Galio", "Pantheon", "Malphite", "Zac"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Vassoura de Aço'?", opcoes: ["Camille", "Fiora", "Irelia", "Vi"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Estímulo'?", opcoes: ["Zilio", "Ekko", "Singed", "Dr. Mundo"], correta: 2 },
    { pergunta: "De quem é a Ultimate 'O Grande Finale'?", opcoes: ["Jhin", "Draven", "Ezreal", "Varus"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Coração de Diamante'?", opcoes: ["Rell", "Taric", "Malphite", "Braum"], correta: 1 },
    { pergunta: "Qual campeão usa a Ultimate 'Paranoia'?", opcoes: ["Nocturne", "Fiddlesticks", "Shaco", "Evelynn"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Tempestade Glacial'?", opcoes: ["Anivia", "Lissandra", "Ashe", "Sejuani"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Vento Sopro'?", opcoes: ["Milío", "Janna", "Yasuo", "Yone"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Rastro de Chamas'?", opcoes: ["Hwei", "Brand", "Annie", "Smolder"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Mããããe!'?", opcoes: ["Smolder", "Kog'Maw", "Gnar", "Nunu"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Cativeiro'?", opcoes: ["Skarner", "Warwick", "Malzahar", "Thresh"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Destruição Mundial'?", opcoes: ["Ryze", "Aurelion Sol", "Xerath", "Karthus"], correta: 1 },
    { pergunta: "De quem é a Ultimate 'Abaixo de Zero'?", opcoes: ["Nunu e Willump", "Anivia", "Lissandra", "Braum"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Ira do Dragão'?", opcoes: ["Lee Sin", "Shyvana", "Aurelion Sol", "Jarvan IV"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Coração da Tempestade'?", opcoes: ["Kennen", "Volibear", "Janna", "Anivia"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Barragem de Chumbo'?", opcoes: ["Graves", "Lucian", "Miss Fortune", "Jhin"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Tiro de Precisão'?", opcoes: ["Ezreal", "Ashe", "Caitlyn", "Senna"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Gatilho Desenfreado'?", opcoes: ["Samira", "Katarina", "Nilah", "Vayne"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Apotheosis'?", opcoes: ["Nilah", "Diana", "Samira", "Karma"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'A Dança das Sombras'?", opcoes: ["Akali", "Zed", "Talon", "Kayn"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Invasão Umbral'?", opcoes: ["Kayn", "Nocturne", "Shaco", "Zed"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Assalto e Bateria'?", opcoes: ["Vi", "Sett", "Lee Sin", "Nautilus"], correta: 0 },
    { pergunta: "Qual campeã usa a Ultimate 'Prisão de Gelo'?", opcoes: ["Sejuani", "Ashe", "Lissandra", "Anivia"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Dominar'?", opcoes: ["Mordekaiser", "Sion", "Renekton", "Nasus"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Portal de Reinos'?", opcoes: ["Ryze", "Bardo", "Twisted Fate", "Ekko"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Truque de Mestre'?", opcoes: ["Shaco", "LeBlanc", "Neeko", "Wukong"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Impacto Chocante'?", opcoes: ["Ziggs", "Corki", "Heimerdinger", "Rumble"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Equalizador'?", opcoes: ["Rumble", "Viktor", "Jayce", "Heimerdinger"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Tempestade Magnética'?", opcoes: ["Viktor", "Blitzcrank", "Orianna", "Rumble"], correta: 1 },
    { pergunta: "Qual campeã possui a Ultimate 'Comando: Onda de Choque'?", opcoes: ["Orianna", "Syndra", "Lulu", "Lux"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Petrificação'?", opcoes: ["Cassiopeia", "Medusa", "Morgana", "Zyra"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Lâmina do Infinito'?", opcoes: ["Master Yi", "Yasuo", "Tryndamere", "Fiora"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Ruptura'?", opcoes: ["Cho'Gath", "Rek'Sai", "Malphite", "Zac"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Mergulho Abissal'?", opcoes: ["Rek'Sai", "Nautilus", "Pyke", "Fizz"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Território Arriscado'?", opcoes: ["Akshan", "Lucian", "Ezreal", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Lamento da Viúva' (Último Carinho)?", opcoes: ["Evelynn", "Morgana", "Elise", "Ahri"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Túmulo Gelado'?", opcoes: ["Lissandra", "Anivia", "Ashe", "Sejuani"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Chuva Estelar'?", opcoes: ["Soraka", "Karthus", "Sona", "Lux"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Super Mega Foguete da Morte!'?", opcoes: ["Jinx", "Ziggs", "Tristana", "Corki"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Bombardeio Incendiário'?", opcoes: ["Corki", "Rumble", "Ziggs", "Gangplank"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'A Caminho do Sul'?", opcoes: ["Kled", "Sion", "Hecarim", "Rammus"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Dança de Flechas' (Terror Crescente)?", opcoes: ["Kindred", "Varus", "Ashe", "Vayne"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Salto de Fé'?", opcoes: ["Illaoi", "Malphite", "Jarvan IV", "Gnar"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Transfusão de Sangue' (Hemoplaga)?", opcoes: ["Vladimir", "Briar", "Warwick", "Swain"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Rastro de Púlvora' (Barragem de Balas)?", opcoes: ["Lucian", "Graves", "Miss Fortune", "Samira"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Domínio da Imperatriz'?", opcoes: ["Bel'Veth", "Rek'Sai", "Kai'Sa", "Zyra"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Assalto da Sombra'?", opcoes: ["Talon", "Zed", "Akali", "Katarina"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Prisão de Cordas' (Amuleto)?", opcoes: ["Amumu", "Rammus", "Skarner", "Sejuani"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Desintegrar'?", opcoes: ["Vel'Koz", "Xerath", "Malzahar", "Kog'Maw"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Ascensão'?", opcoes: ["Kayle", "Morgana", "Pantheon", "Leona"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Fúria do Dragão' (Voo)?", opcoes: ["Shyvana", "Aurelion Sol", "Lee Sin", "Jarvan IV"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Estilhaçar'?", opcoes: ["Rell", "Taric", "Braum", "Leona"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Mundo de Sombras'?", opcoes: ["Nocturne", "Mordekaiser", "Senna", "Vex"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Impacto Meteoro'?", opcoes: ["Pantheon", "Galio", "Malphite", "Zac"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Grande Estrela Cadente'?", opcoes: ["Aurelion Sol", "Pantheon", "Soraka", "Taric"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Sopro de Luz'?", opcoes: ["Aurelion Sol", "Smolder", "Shyvana", "Brand"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Gatilho do Caos'?", opcoes: ["Samira", "Jinx", "Vayne", "Kai'Sa"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Destino Selado'?", opcoes: ["Yone", "Yasuo", "Zed", "Talon"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Selo de Malícia'?", opcoes: ["LeBlanc", "Neeko", "Zoe", "Ahri"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Salto Devastador'?", opcoes: ["Zac", "Malphite", "Cho'Gath", "Gnar"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Vassoura de Aço'?", opcoes: ["Camille", "Irelia", "Fiora", "Vi"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Coração de Diamante' (Esplendor Cósmico)?", opcoes: ["Taric", "Leona", "Braum", "Rell"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Fúria das Areias'?", opcoes: ["Nasus", "Renekton", "Azir", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Dominar'?", opcoes: ["Renekton", "Nasus", "Sion", "Volibear"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Ruptura'?", opcoes: ["Cho'Gath", "Rek'Sai", "Malphite", "Zac"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Grito Primordial'?", opcoes: ["Gnar", "Cho'Gath", "Warwick", "Volibear"], correta: 1 },
    { pergunta: "Qual campeão usa a Ultimate 'Invasão Umbral'?", opcoes: ["Kayn", "Zed", "Talon", "Nocturne"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Tiro de Precisão'?", opcoes: ["Ezreal", "Caitlyn", "Jinx", "Ashe"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Truque de Mestre'?", opcoes: ["Shaco", "Wukong", "LeBlanc", "Neeko"], correta: 1 },
    { pergunta: "Qual campeão usa a Ultimate 'Paranoia'?", opcoes: ["Nocturne", "Shaco", "Fiddlesticks", "Evelynn"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Soco de Alavanca'?", opcoes: ["Vi", "Sett", "Lee Sin", "Nautilus"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Grito do Carniceiro'?", opcoes: ["Urgot", "Sion", "Singed", "Warwick"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Tempestade Magnética'?", opcoes: ["Viktor", "Blitzcrank", "Orianna", "Jayce"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Morte Expressa'?", opcoes: ["Zeri", "Jinx", "Ezreal", "Lucian"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Poeira Estelar' (Queda Estelar)?", opcoes: ["Soraka", "Aurelion Sol", "Taric", "Zoe"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Salto Dimensional'?", opcoes: ["Zoe", "Kassadin", "Ezreal", "Ekko"], correta: 0 },
    { pergunta: "Qual campeã tem a Ultimate 'Abraço da Viúva' (Cárcere de Espinhos)?", opcoes: ["Zyra", "Evelynn", "Morgana", "LeBlanc"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Ira da Natureza'?", opcoes: ["Maokai", "Ivern", "Malphite", "Zyra"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Mergulho da Falange'?", opcoes: ["Pantheon", "Jarvan IV", "Xin Zhao", "Leona"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Desafio Grandioso'?", opcoes: ["Fiora", "Camille", "Irelia", "Jax"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Lâminas da Vanguarda'?", opcoes: ["Irelia", "Akali", "Katarina", "Talon"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Chacina Dinástica'?", opcoes: ["Nasus", "Renekton", "Azir", "Sivir"], correta: 1 },
    { pergunta: "Qual campeão possui a Ultimate 'Decreto do Imperador'?", opcoes: ["Azir", "Nasus", "Xerath", "Jarvan IV"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Ritual Arcano'?", opcoes: ["Xerath", "Vel'Koz", "Karthus", "Ryze"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Chuva de Disparos'?", opcoes: ["Miss Fortune", "Lucian", "Gangplank", "Samira"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Lótus da Morte'?", opcoes: ["Katarina", "Samira", "Akali", "Nilah"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Túmulo de Areia'?", opcoes: ["Skarner", "Nasus", "Azir", "Malzahar"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Prisão de Cordas'?", opcoes: ["Amumu", "Sejuani", "Leona", "Skarner"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Enclausurar' (Cárcere de Gelo)?", opcoes: ["Sejuani", "Lissandra", "Ashe", "Anivia"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'O Chamado do Destino'?", opcoes: ["Kalista", "Thresh", "Senna", "Lucian"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Soco de Alavanca'?", opcoes: ["Vi", "Sett", "Blitzcrank", "Lee Sin"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Cataclismo'?", opcoes: ["Jarvan IV", "Malphite", "Taliyah", "Yorick"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Barragem de Canhão'?", opcoes: ["Gangplank", "Miss Fortune", "Corki", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Grito do Carniceiro'?", opcoes: ["Urgot", "Sion", "Dr. Mundo", "Singed"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Glória na Morte'?", opcoes: ["Sion", "Karthus", "Yorick", "Mordekaiser"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Impacto Chocante'?", opcoes: ["Ziggs", "Heimerdinger", "Corki", "Rumble"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Aperto Infernal'?", opcoes: ["Malzahar", "Warwick", "Skarner", "Thresh"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Invasão Umbral'?", opcoes: ["Kayn", "Nocturne", "Zed", "Talon"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Destino Selado'?", opcoes: ["Yone", "Yasuo", "Zed", "Shen"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Domínio das Sombras'?", opcoes: ["Zed", "Akali", "Talon", "Nocturne"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Monção'?", opcoes: ["Janna", "Soraka", "Nami", "Lulu"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Crescendo'?", opcoes: ["Sona", "Seraphine", "Bardo", "Rakan"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Ritual de Sangue' (Hemoplaga)?", opcoes: ["Vladimir", "Briar", "Swain", "Warwick"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Vassoura de Aço'?", opcoes: ["Camille", "Fiora", "Irelia", "Vi"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Paraíso'?", opcoes: ["Shen", "Soraka", "Galio", "Pantheon"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Grande Entrada'?", opcoes: ["Rakan", "Alistar", "Braum", "Sett"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'A Caminho do Sul'?", opcoes: ["Kled", "Sion", "Hecarim", "Rammus"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Terror Crescente'?", opcoes: ["Kindred", "Fiddlesticks", "Nocturne", "Hecarim"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Salto de Fé'?", opcoes: ["Illaoi", "Malphite", "Zac", "Jarvan IV"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Estímulo'?", opcoes: ["Singed", "Mundo", "Twitch", "Warwick"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Massacre'?", opcoes: ["Master Yi", "Aatrox", "Olaf", "Tryndamere"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'O Show deve Continuar'?", opcoes: ["Sett", "Vi", "Lee Sin", "Braum"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Soco de Alavanca'?", opcoes: ["Vi", "Sett", "Lee Sin", "Blitzcrank"], correta: 0 },
    { pergunta: "Qual campeão possui a Ultimate 'Execução Pública'?", opcoes: ["Ambessa", "Darius", "Draven", "Urgot"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'A Caminho do Mar'?", opcoes: ["Bel'Veth", "Nami", "Fizz", "Nautilus"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Turbilhão de Lâminas'?", opcoes: ["Nilah", "Samira", "Katarina", "Diana"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'Abraço do Infinito'?", opcoes: ["Naafiri", "Warwick", "Rengar", "Kha'Zix"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Sopro de Vida'?", opcoes: ["Milio", "Soraka", "Janna", "Yuumi"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Pintura Final'?", opcoes: ["Hwei", "Ahri", "Neeko", "Lux"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Mããããe!'?", opcoes: ["Smolder", "Kog'Maw", "Gnar", "Annie"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Maldição Carmesim'?", opcoes: ["Briar", "Vladimir", "Warwick", "Swain"], correta: 0 },
    { pergunta: "Qual campeão tem a Ultimate 'A Caminho do Herói'?", opcoes: ["K'Sante", "Jax", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "Qual campeã possui a Ultimate 'Capítulo Final'?", opcoes: ["Yuumi", "Sona", "Seraphine", "Lux"], correta: 0 },
    { pergunta: "De quem é a Ultimate 'Lamento da Viúva'?", opcoes: ["Evelynn", "Morgana", "Elise", "Ahri"], correta: 0 },
    { pergunta: "Qual campeão usa a Ultimate 'Possessão Dominante'?", opcoes: ["Viego", "Sylas", "Mordekaiser", "Yorick"], correta: 0 }
];
    
